DROP VIEW IF EXISTS WorksView;

DROP VIEW IF EXISTS CatalogView;

DROP TABLE IF EXISTS Pages;

DROP TABLE IF EXISTS Chapters;

DROP TABLE IF EXISTS Works;

DROP TABLE IF EXISTS MiscFiles;

VACUUM;